-- Festival Ms.Sign
local s,id=GetID()
function s.initial_effect(c)
    aux.EnableExtraRules(c,s,s.op)
end
--Extra rules function
function s.op(c)
    --cannot attack
    local e0=Effect.CreateEffect(c)
    e0:SetType(EFFECT_TYPE_FIELD)
    e0:SetCode(EFFECT_CANNOT_ATTACK)
    e0:SetProperty(EFFECT_FLAG_IGNORE_IMMUNE)
    e0:SetTargetRange(LOCATION_MZONE,LOCATION_MZONE)
    e0:SetReset(RESET_PHASE+PHASE_END,3)
    Duel.RegisterEffect(e0,0)
    --no level 4 or 5
    local e1=Effect.CreateEffect(c)
    e1:SetType(EFFECT_TYPE_FIELD)
    e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET+EFFECT_FLAG_CLIENT_HINT+EFFECT_FLAG_IGNORE_IMMUNE)
    e1:SetCode(EFFECT_CANNOT_SUMMON)
    e1:SetReset(RESET_PHASE+PHASE_END,4)
    e1:SetTargetRange(1,1)
    e1:SetTarget(function(e,c) return c:IsLevel(4) or c:IsLevel(5) end)
    Duel.RegisterEffect(e1,0)
    local e2=e1:Clone()
    e2:SetCode(EFFECT_CANNOT_FLIP_SUMMON)
    Duel.RegisterEffect(e2,0)
    local e3=e1:Clone()
    e3:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
    Duel.RegisterEffect(e3,0)
    local e4=e1:Clone()
    e4:SetCode(EFFECT_CANNOT_MSET)
    Duel.RegisterEffect(e4,0)
    local e5=e1:Clone()
    e5:SetCode(EFFECT_CANNOT_SSET)
    Duel.RegisterEffect(e5,0)
    --no direct
    local e6=Effect.CreateEffect(c)
    e6:SetType(EFFECT_TYPE_FIELD)
    e6:SetCode(EFFECT_CANNOT_DIRECT_ATTACK)
    e6:SetProperty(EFFECT_FLAG_IGNORE_IMMUNE)
    e6:SetTargetRange(LOCATION_MZONE,LOCATION_MZONE)
    e6:SetReset(RESET_PHASE+PHASE_END,5)
    Duel.RegisterEffect(e6,0)
    --no level 6+
    local e7=Effect.CreateEffect(c)
    e7:SetType(EFFECT_TYPE_FIELD)
    e7:SetProperty(EFFECT_FLAG_PLAYER_TARGET+EFFECT_FLAG_CLIENT_HINT+EFFECT_FLAG_IGNORE_IMMUNE)
    e7:SetCode(EFFECT_CANNOT_SUMMON)
    e7:SetReset(RESET_PHASE+PHASE_END,7)
    e7:SetTargetRange(1,1)
    e7:SetTarget(function(e,c) return c:IsLevelAbove(6) end)
    Duel.RegisterEffect(e7,0)
    local e8=e7:Clone()
    e8:SetCode(EFFECT_CANNOT_FLIP_SUMMON)
    Duel.RegisterEffect(e8,0)
    local e9=e7:Clone()
    e9:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
    Duel.RegisterEffect(e9,0)
    local e10=e7:Clone()
    e10:SetCode(EFFECT_CANNOT_MSET)
    Duel.RegisterEffect(e10,0)
    local e11=e7:Clone()
    e11:SetCode(EFFECT_CANNOT_SSET)
    Duel.RegisterEffect(e11,0)
    --faceup def
    local e12=Effect.GlobalEffect()
    e12:SetType(EFFECT_TYPE_FIELD)
    e12:SetCode(EFFECT_LIGHT_OF_INTERVENTION)
    e12:SetProperty(EFFECT_FLAG_PLAYER_TARGET+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
    e12:SetTargetRange(1,1)
    Duel.RegisterEffect(e12,0)
    --Double LP
    Duel.SetLP(0,10000)
    Duel.SetLP(1,10000)
end